package sh.sysl

/** The C header for whatever a module `@export`ed (`reference/ffi.md § @export`).
 *
 * **It is a translation of one signature at a time and nothing more.** `ExportCheck` has already
 * held every exported function to a signature C can spell, so there is no type here that needs a
 * decision — each one has exactly one C spelling and this writes it down. That is the whole reason
 * the header is the last of the three pieces and the cheapest: the marking is what does the work,
 * and a header is what the marking makes mechanical.
 *
 * **`<stdint.h>` and `<stdbool.h>` rather than `int` and `long`.** C's own integer names say what a
 * type is *at least*, and sysl's say what it *is* — an `i32` is thirty-two bits everywhere, and
 * writing it `int` would be right on every machine anyone is likely to use and wrong as a claim.
 * The fixed-width names mean what sysl means, so the header states the actual contract.
 *
 * **What the header assumes of its consumer: C99, or any C++.** The three includes are C99's, and
 * nothing else here needs more — the one construct that would, the no-return annotation, is written
 * through a macro that resolves to C11's `_Noreturn`, C++11's `[[noreturn]]`, or nothing at all.
 * That last case loses an optimization and stays valid, which is the right way round: a header that
 * a consumer's compiler refuses is worse than one that tells it slightly less.
 */
object CHeader {

  /** The header for a compiled module: a guard, the two includes, and one prototype per export in
   * the order the functions were declared.
   *
   * `name` is what the include guard is built from — the project's name, so two headers in one C
   * project do not collide. Anything not a C identifier is replaced, since a guard is a macro name
   * and a project may be called what it likes.
   */
  def render(funcs: List[TFunc], name: String): String = {
    val exports = funcs.filter(_.exported.isDefined).sortBy(_.exported.get)
    val guard   = s"SYSL_${name.map(c => if c.isLetterOrDigit then c.toUpper else '_')}_H"
    val out     = new StringBuilder

    out ++= s"/* Generated by sysl. The declarations a C project needs to call into this module. */\n"
    out ++= s"#ifndef $guard\n#define $guard\n\n"
    out ++= "#include <stdbool.h>\n#include <stdint.h>\n#include <stddef.h>\n\n"

    if exports.exists(f => Type.repr(f.retTy) == Type.Never) then out ++= noreturnMacro

    out ++= "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"

    // The aggregates the prototypes below name, defined before anything uses one. They are emitted
    // in dependency order — a struct with a struct in it comes after what it holds — because C
    // needs a complete type to lay a member out, and there is nothing here to forward-declare
    // around: a by-value member is the case a forward declaration does not serve.
    for t <- aggregates(exports) do out ++= s"${definition(t)}\n"

    if exports.isEmpty then
      // A header with nothing in it is worth writing rather than refusing: a build that exported
      // nothing is a build whose author forgot the attribute, and an empty header says so where a
      // missing file would read as a step that had not run.
      out ++= "/* This module exports nothing — no function in it is marked '@export'. */\n\n"
    else for f <- exports do out ++= s"${prototype(f)};\n"

    if exports.nonEmpty then out ++= "\n"

    out ++= "#ifdef __cplusplus\n}\n#endif\n\n"
    out ++= s"#endif /* $guard */\n"
    out.toString
  }

  /** The no-return annotation, written once per header and only where something needs it.
   *
   * It is a macro rather than the keyword itself because the header serves two languages: `_Noreturn`
   * is C11's spelling and is not valid C++ at all, while the `extern "C"` block below says a C++
   * consumer is expected. Guarding on the version leaves an older compiler with an empty definition,
   * which is a weaker declaration and not a broken one.
   *
   * `#ifndef` because a project may include two of these headers, and a macro defined twice is a
   * warning where the include guard would not have helped — that one is per project name.
   */
  private val noreturnMacro: String =
    """#ifndef SYSL_NORETURN
      |#if defined(__cplusplus) && __cplusplus >= 201103L
      |#define SYSL_NORETURN [[noreturn]]
      |#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
      |#define SYSL_NORETURN _Noreturn
      |#else
      |#define SYSL_NORETURN
      |#endif
      |#endif
      |
      |""".stripMargin

  /** One function, as C declares it. A parameter keeps the name sysl gave it — a prototype's names
   * are documentation and nothing else, and the reader is better served by `count` than by nothing.
   *
   * **A `never` result is annotated, and a `unit` one is not**, though both spell as `void`. That
   * difference is the only thing distinguishing the two on this side of the boundary: `never` says
   * control does not come back (`reference/types.md § unit and never`), which lets the caller's
   * compiler drop the code after the call and stop asking about paths that end in it. Rendered as a
   * bare `void` it would be the strictly weaker claim `unit` already makes.
   */
  def prototype(f: TFunc): String = {
    val params =
      if f.params.isEmpty then "void"
      else f.params.map((n, t) => declare(t, n)).mkString(", ")

    val noReturn = if Type.repr(f.retTy) == Type.Never then "SYSL_NORETURN " else ""

    // The function's own name and parameter list are the declarator its result type wraps, which is
    // what puts a returned function pointer's `(*` … `)` around them: `void (*get(void))(int32_t)`.
    s"$noReturn${declare(f.retTy, s"${f.exported.get}($params)")}"
  }

  /** Every named aggregate the exported signatures reach, **innermost first**.
   *
   * A struct is reached through a parameter, a result, a pointer's pointee, a function pointer's own
   * signature, another struct's field, or an array's element — so the walk follows all of them
   * rather than only the top level, and a type mentioned twice is defined once.
   *
   * It is public because `Exports.names` asks the same question — which types land in the header —
   * in order to refuse two of them claiming one name. Working that set out a second time is how the
   * check and the header would come to disagree about what is in it.
   */
  def aggregates(exports: List[TFunc]): List[Type] = {
    val seen  = scala.collection.mutable.LinkedHashSet.empty[Type]
    val named = scala.collection.mutable.ListBuffer.empty[Type]

    def walk(t: Type): Unit =
      val r = Type.repr(t)

      if !seen.add(r) then ()
      else
        r match
          case s: Type.Struct =>
            // The fields go first, so that what this definition lays out is already complete where
            // the C compiler reads it. An opaque struct lays nothing out, so what its fields reach
            // is not the header's business — and a field type with no C spelling is no obstacle.
            if !s.opaque then s.stored.foreach((_, f) => walk(f))
            named += s
          case a: Type.Array          => walk(a.elem)
          case Type.Ptr(inner)        => walk(inner)
          case Type.CFn(params, ret)  => params.foreach(walk); walk(ret)
          case _                      => ()

    for f <- exports do
      f.params.foreach((_, t) => walk(t))
      walk(f.retTy)

    named.toList
  }

  /** One aggregate, as C declares it — a `typedef` of an anonymous struct, so that the name is
   * usable without the `struct` keyword and reads the way a C API's own handles do.
   *
   * **An `opaque` struct is declared incomplete** — `typedef struct h h;`, a tag with no body — which
   * is exactly C's `struct foo;` (`reference/ffi.md § opaque`). The C caller is outside the declaring
   * module, so it may hold a `*h` and never see inside; the tag is what makes the type nameable
   * without a layout, where an anonymous struct has nothing to be incomplete about.
   */
  private def definition(t: Type): String = t match
    case s: Type.Struct if s.opaque => s"typedef struct ${cName(s)} ${cName(s)};\n"
    case s: Type.Struct =>
      val fields = s.stored.map((n, f) => s"\t${member(f, n)};\n").mkString

      s"typedef struct {\n$fields} ${cName(s)};\n"
    case _ => ""

  /** A field, which is a declaration like any other: `declare` puts an array's brackets and a
   * function pointer's `(*` … `)` around the name where C wants them.
   */
  private def member(t: Type, name: String): String = declare(t, name)

  /** A sysl type declaring `name` — a parameter, a field, or (with `name` holding the function's own
   * name and parameter list) a whole prototype.
   *
   * **C does not write a type and then a name.** The name is the innermost part of a *declarator*
   * that the type wraps around it: an array's `[n]` and a function's parameter list go after it, a
   * pointer's `*` goes before it, and a function pointer is the two together, `R (*name)(A)`.
   * Spelling the type whole and appending the name gives `void (*)(int32_t) f`, which no C compiler
   * accepts. So this builds the declarator outward from the name, and `spell` is the same walk with
   * no name at all — C's *abstract* declarator, `void (*)(int32_t)`.
   */
  def declare(t: Type, name: String): String = Type.repr(t) match
    case Type.CFn(params, ret) =>
      val ps = if params.isEmpty then "void" else params.map(spell).mkString(", ")
      declare(ret, s"(*$name)($ps)")
    // A pointer to something whose declarator binds tighter than `*` — an array or a function
    // pointer — needs the parentheses that make the `*` apply first.
    case Type.Ptr(inner) =>
      Type.repr(inner) match
        case _: Type.Array | _: Type.CFn => declare(inner, s"(*$name)")
        case _                           => declare(inner, if name.isEmpty then "*" else s"* $name")
    case a: Type.Array => declare(a.elem, s"$name[${a.length}]")
    case _             => if name.isEmpty then base(t) else s"${base(t)} $name"

  /** The C name of a named type — the one the author chose, or the derived one.
   *
   * **`@export("b2BodyId")` on the struct is what chooses it** (`reference/ffi.md § @export`), and
   * it exists because everything else in this header is either the author's spelling or a C
   * fixed-width name: a binding mirroring a C library wants to hand back that library's own type
   * names. The choice is a claim, so `Exports.names` holds it to the property the derived form
   * gives away — that no two types in one header answer to one name.
   *
   * Derived, the mangled form is already unique per instantiation — it is what the emitted IR names
   * the aggregate — and the separators it uses are not C identifier characters, so they are replaced
   * rather than the name being invented again here.
   *
   * **The replacement is where uniqueness stops, which is worth knowing before trusting the derived
   * form.** `Type.mangled` is injective and the map onto `_` is not: a `C` in module `a.b` and a
   * `b_C` in module `a` mangle apart and land on `a_b_C` together. It has never been reachable in
   * practice and it was never checked, and `Exports.names` now catches it — so the honest statement
   * is that the derived name is *ordinarily* unique and the collision rule is what guarantees it.
   */
  def cName(t: Type): String = t match
    case s: Type.Struct if s.cname.isDefined => s.cname.get
    case n: Type.Named =>
      Type.mangled(n.base, n.targs).map(c => if c.isLetterOrDigit then c else '_')
    case _ => "void"

  /** A sysl type as C spells it.
   *
   * Only the types `ExportCheck.crosses` admits reach here, so the fallthrough is unreachable rather
   * than a default — and it is written as a refusal in the text it produces, because a header that
   * quietly emitted `void*` for something it did not understand would compile on both sides and be
   * wrong in between.
   */
  def spell(t: Type): String = declare(t, "")

  /** A type that is not built from a declarator — a scalar, a struct's name, a simple enum's
   * integer. Pointers, arrays and function pointers are `declare`'s, since they wrap a name.
   */
  private def base(t: Type): String = Type.repr(t) match
    case Type.Unit | Type.Never              => "void"
    case Type.Bool                           => "bool"
    // A `char` is a Unicode scalar value, which is four bytes and not C's `char`. `uint32_t` is what
    // it is; C's own name for that idea is `char32_t`, which needs a header C99 does not have.
    case Type.Char                           => "uint32_t"
    case Type.Integer(bits, signed, _)       => s"${if signed then "" else "u"}int${bits}_t"
    // The two sixteen-bit formats have C names of their own, and neither of them is a `float`.
    // Spelling either as a wider type would compile on both sides of the header and then pass a
    // value of one width where the callee reads another, which is the single failure a generated
    // header exists to make impossible.
    case Type.Floating(16, true)             => "__bf16"
    case Type.Floating(16, _)                => "_Float16"
    case Type.Floating(32, _)                => "float"
    case Type.Floating(_, _)                 => "double"
    // A struct is named rather than written out, and `aggregates` is what put the definition above
    // this prototype (0137). A **simple** enum is its underlying integer and is spelled as one: C's
    // own `enum` has an implementation-defined width, so naming the integer is what states the same
    // contract the rest of this header states.
    case s: Type.Struct                      => cName(s)
    case e: Type.Enum if e.simple            => spell(e.underlying)
    case other                               => s"/* no C spelling for ${other} */ void"
}
